name: Cassandra Fluent library

on:
  push:
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'

    - name: Run resotre
      run: dotnet restore
    
    - name: Run build
      run: dotnet build

  test:
    needs: build
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'

    - name: Run build
      run: dotnet build
    
    - name: Run Cassandra Docker
      run: docker run --name cfm-database -e CASSANDRA_CLUSTER_NAME=cfm-cluster -p 9042:9042 -d cassandra:latest
    
    - name: Get Docker IP
      run: docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' cfm-database
    
    - name: Run tests
      run: dotnet test