name: Cassandra Fluent library

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet: ["3.1.x", "5.0.x", "7.0.x"]

    services:
      cfm-cassandra:
        image: cassandra:latest
        ports:
          - 9042:9042

        env:
          CASSANDRA_CLUSTER_NAME: cfm-cluster

        options: --health-cmd "cqlsh --debug" --health-interval 10s --health-retries 10

    steps:
      - uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Restoring packages
        run: dotnet restore

      - name: Building
        run: dotnet build --configuration Release --no-restore

      - name: Testing
        run: dotnet test --no-restore --collect:"XPlat Code Coverage" --results-directory ./TestResults/.coverage
