name: Cassandra Fluent library

on:
  push:
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Run resotre
      run: dotnet restore
    
    - name: Run build
      run: dotnet build

  test:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - uses: fabasoad/setup-cassandra-action@v1.0.0
      with:
        host: 'localhost'
        port: 9042
        username: Cassandra
        password: Cassandra
        connect-timeout: 30
        keyspace: test

    - name: Run tests
      run: dotnet test