name: Cassandra Fluent library

on:
  push:
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Run resotre
      run: dotnet restore
    
    - name: Run build
      run: dotnet build

  test:
    needs: build
    runs-on: ubuntu-latest

    services:
      cfm-cassandra:
        image: cassandra:latest
        ports:
          - 9042:9042
        
        env: 
          CASSANDRA_CLUSTER_NAME: cfm-cluster

        options: --health-cmd "cqlsh --debug" --health-interval 5s --health-retries 10
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
   
    - name: Run tests
      run: dotnet test