name: Cassandra Fluent library

on:
  push:
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Run resotre
      run: dotnet restore
    
    - name: Run build
      run: dotnet build

  test:
    needs: build
    runs-on: ubuntu-latest
    
    container:
      image: mcr.microsoft.com/dotnet/core/sdk:3.1
    
    services:
      cfm-cassandra:
        image: cassandra:latest
        env:
          CASSANDRA_CLUSTER_NAME: cfm-cluster
        ports:
        - 9042:9042

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - run: echo ${{ job.services.cassandra.id }}

    - name: Check
      run: cat ./Cassandra.Fluent.Migrator.Tests/Settings/appsettings.tests.json

    - name: Run tests
      run: dotnet test